name: Docker Image CI

on:
  push:
    branches: [ division ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x, 16.x]
        
    steps:
    -
      uses: actions/checkout@v2
    -
      name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - 
      name: Install dependencies
      working-directory: app
      run: npm ci
    -
      name: Build App
      working-directory: app
      run: npm run build --if-present
    -
      name: Testing App
      working-directory: app
      run: npm test

